<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Modules\Identity\ShopFlow.Modules.Identity\ShopFlow.Modules.Identity.csproj" />
    <ProjectReference Include="..\Modules\Catalog\ShopFlow.Modules.Catalog\ShopFlow.Modules.Catalog.csproj" />
    <ProjectReference Include="..\Modules\Inventory\ShopFlow.Modules.Inventory\ShopFlow.Modules.Inventory.csproj" />
    <ProjectReference Include="..\Modules\Inventory\ShopFlow.Inventory.GrpcClient\ShopFlow.Inventory.GrpcClient.csproj" />
    <ProjectReference Include="..\Modules\Ordering\ShopFlow.Modules.Ordering\ShopFlow.Modules.Ordering.csproj" />
    <ProjectReference Include="..\Modules\Payment\ShopFlow.Modules.Payment\ShopFlow.Modules.Payment.csproj" />
    <ProjectReference Include="..\Modules\Notification\ShopFlow.Modules.Notification\ShopFlow.Modules.Notification.csproj" />
    <ProjectReference Include="..\ShopFlow.BuildingBlocks\ShopFlow.BuildingBlocks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Aws.S3" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>

