<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Identity\ShopFlow.Modules.Identity\ShopFlow.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\ShopFlow.Modules.Catalog\ShopFlow.Modules.Catalog.csproj" />
    <ProjectReference Include="..\..\src\Modules\Inventory\ShopFlow.Modules.Inventory\ShopFlow.Modules.Inventory.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ordering\ShopFlow.Modules.Ordering\ShopFlow.Modules.Ordering.csproj" />
    <ProjectReference Include="..\..\src\Modules\Payment\ShopFlow.Modules.Payment\ShopFlow.Modules.Payment.csproj" />
    <ProjectReference Include="..\..\src\Modules\Notification\ShopFlow.Modules.Notification\ShopFlow.Modules.Notification.csproj" />
    <ProjectReference Include="..\..\src\ShopFlow.Host\ShopFlow.Host.csproj" />
  </ItemGroup>

</Project>
